'ABS_PATH': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api'
'ADMIN_ROUTE': '/admin'
'API_KEY': 'dccf3bb69a3c3692c345cb514d258028ad397f619127e9faa07c831a317aa447'
'API_KEY_ENABLED': !!bool 'false'
'BERT_BASE_JAPANESE_V3': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/bert-base-japanese-v3'
'BERT_LARGE_JAPANESE_V2': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/bert-large-japanese-v2'
'CACHE_PATH': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api/cache'
'CHINESE_ROBERTA_WWM_EXT_LARGE': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/chinese-roberta-wwm-ext-large'
'CLEAN_INTERVAL_SECONDS': !!int '3600'
'DEBERTA_V2_LARGE_JAPANESE': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/deberta-v2-large-japanese'
'DEBERTA_V2_LARGE_JAPANESE_CHAR_WWM': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/deberta-v2-large-japanese-char-wwm'
'DEBERTA_V3_LARGE': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/bert/deberta-v3-large'
'DEBUG': !!bool 'false'
'DEVICE': !torch.device 'cuda'
'DYNAMIC_LOADING': !!bool 'false'
'ESPEAK_LIBRARY': ''
'IS_ADMIN_ENABLED': !!bool 'true'
'JSON_AS_ASCII': !!bool 'false'
'LANGUAGE_AUTOMATIC_DETECT': []
'LANGUAGE_IDENTIFICATION_LIBRARY': 'langid'
'LOGGING_LEVEL': 'DEBUG'
'LOGS_BACKUPCOUNT': !!int '30'
'LOGS_PATH': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api/logs'
'MAX_CONTENT_LENGTH': !!int '5242880'
'PORT': !!int '23456'
'SAVE_AUDIO': !!bool 'false'
'SECRET_KEY': '41f42b8c2f41fb579410ca8f8e7f7e36797c5aedfecc2dfd6bc827cf08d17503'
'UPLOAD_FOLDER': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api/upload'
'VITS_CHINESE_BERT': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apivits/bert'
'WAV2VEC2_LARGE_ROBUST_12_FT_EMOTION_MSP_DIM': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-apibert_vits2/emotional/wav2vec2-large-robust-12-ft-emotion-msp-dim'
'default_parameter':
  'format': 'wav'
  'id': !!int '0'
  'lang': 'auto'
  'length': !!int '1'
  'length_en': !!int '0'
  'length_ja': !!int '0'
  'length_zh': !!int '0'
  'noise': !!float '0.33'
  'noisew': !!float '0.4'
  'sdp_ratio': !!float '0.2'
  'segment_size': !!int '50'
  'style_weight': !!float '0.7'
'model_config':
  'dimensional_emotion_npy': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api/Model/npy'
  'hubert_soft_model': 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api/Model/hubert-soft-0d54a1f4.pt'
  'model_list':
  - - 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api\Model\bert_vits2\naxida\G_5100.pth'
    - 'D:\MeidoAGI\MeidoAGI\vits\vits-simple-api\Model\bert_vits2\naxida\config.json'
'users':
  'admin':
    'admin': !User
      'id': !!int '1'
      'password': 'c8TBaOsOp1zkXCyU'
      'username': 'IDtgBbR6'
